### ISSUE TITLE
Settings page error - Redline 4.0.7

### ISSUE THREAD

**Issue by im-ikao** [future-architect/redmine_gitlab_adapter#1]
ActionView::Template::Error (uninitialized constant #<Class:0x00005559b9c22bb8>::Gitlab):
    10:     <th><%= l(:text_scm_command_version) %></th>
    11:   </tr>
    12:   <% Redmine::Scm::Base.all.collect do |choice| %>
    13:     <% scm_class = "Repository::#{choice}".constantize %>
    14:     <% text, value = (choice.is_a?(Array) ? choice : [choice, choice]) %>
    15:     <% setting = :enabled_scm %>
    16:     <% enabled = Setting.send(setting).include?(value) %>
  
app/views/settings/_repositories.html.erb:13:in `block (2 levels) in _app_views_settings__repositories_html_erb__1351165689430309301_46921946125160'
app/views/settings/_repositories.html.erb:12:in `collect'
app/views/settings/_repositories.html.erb:12:in `block in _app_views_settings__repositories_html_erb__1351165689430309301_46921946125160'
app/views/settings/_repositories.html.erb:1:in `_app_views_settings__repositories_html_erb__1351165689430309301_46921946125160'
app/views/common/_tabs.html.erb:17:in `block in _app_views_common__tabs_html_erb__1227372980101744441_46921921741860'
app/views/common/_tabs.html.erb:16:in `each'
app/views/common/_tabs.html.erb:16:in `_app_views_common__tabs_html_erb__1227372980101744441_46921921741860'
app/helpers/application_helper.rb:386:in `render_tabs'
app/views/settings/edit.html.erb:5:in `_app_views_settings_edit_html_erb__2408847084055145564_46921921812260'
app/controllers/settings_controller.rb:31:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by komatsuyuji** [comment]
Did you run 'bundle install' to install ruby llibrary [gitlab v4.14.0](https://rubygems.org/gems/gitlab/versions/4.14.0).
Please read the installation of [README.md](https://github.com/future-architect/redmine_gitlab_adapter).
