### ISSUE TITLE
Redmine 5.X compatibility

### ISSUE THREAD

**Issue by guillermoml** [future-architect/redmine_gitlab_adapter#3]
Hi, I tried to install this plugin in a bitnami vw:
- Redmine version                5.0.2.stable
- Ruby version                   3.0.4-p208 (2022-04-12) [x86_64-linux]
- Rails version                  6.1.6

After executing _bundle install_ and then _bundle exec rake redmine:plugins NAME=redmine_gitlab_adapter  RAILS_ENV=production_ I get this error:
```
rake aborted!
LoadError: cannot load such file -- gitlab_repositories_helper_patch
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/opt/bitnami/redmine/plugins/redmine_gitlab_adapter/init.rb:2:in `<top (required)>'
/opt/bitnami/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/opt/bitnami/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/opt/bitnami/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/opt/bitnami/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
.....
```
After seeing _zeitwerk_ in the log I suppose that this plugin isn't Redmine 5.x compatible, or I'm doing something wrong?

Best regards

**Comment by guillermoml** [comment]
There is a fork that is Redmine 5.X compatible: https://github.com/kattoshi/redmine_gitlab_adapter/tree/5.0.x
You have to clone the  **5.0.x branch**. Tested with a bitnami VM with Redmine 5.0.2.stable

**Comment by komatsuyuji** [comment]
Thank you so much.
